#!/bin/bash

usage_error () {
  cat << EOF
--------------------------------------------------------------------------------------------------------
Name: chadu
chadu means jump
--------------------------------------------------------------------------------------------------------
Description
--------------------------------------------------------------------------------------------------------
Used jump directly to any inner recursive directory
use as: 'chadu <dir-name/part of dir-name>'

Suppose you are in '/home/jophine/jack/' and you need to jump to '/home/jophine/jack/fetch/water/pot'
just use 'chadu pot' or 'chadu po'
You will have a list of options like:
0 /home/jophine/jack/fetch/water/pot
1 /home/jophine/jack/drink/water/pot
2 /home/jophine/jack/fetch/lake/pot
3 /home/jophine/jack/drink/ice/pot
now choose 0 and give ENTER

--------------------------------------------------------------------------------------------------------
EOF
}
SHELL_NAME=`basename $SHELL`
if [ $SHELL_NAME = "zsh" ]
then
  sindex=0
else
  sindex=-1
fi
if [ -z "$1" ]
then
  usage_error
else
  if [ $1 = '-h' ] || [ $1 = '--help' ]
  then
    usage_error
  else
    pathCount=$sindex
    if [ $SHELL_NAME = "zsh" ]
    then
      pathList=($(find -iname "$1*" -type d))
    else
      IFS01=IFS
      IFS=$","
      pathList=`find -iname "$1*" -type d|tr "\\n" ","`
    fi
    for path in $pathList
    do
      pathCount=$[$pathCount + 1]
      paths[$pathCount]=$path
    done
    if [ $pathCount -eq -1 ]
    then
      echo "No such occurrence"
    else
      if [ $pathCount -eq $(($sindex+1)) ]
      then
        cd ${paths[$pathCount]}
      else
        for ((i=$sindex+1; i<=$pathCount; i++))
        do
          echo $i ${paths[$i]}
        done
        if [ $SHELL_NAME = "zsh" ]
        then
          vared -p "Enter the path number: " -c select
        else
          read -p "Enter the path number: " select
        fi
        if [ $select -ge 0 ] && [ $select -le $pathCount ]
        then
          cd ${paths[$select]}
        else
          echo "Choose correct path number"
        fi
      fi
    fi
    if [ $SHELL_NAME != "zsh" ]
    then
      IFS=$IFS01
    fi
  fi
fi
