#!/bin/sh

echo "Started downloading 'chadu' from github.."
wget -O /bin/chadu https://raw.github.com/jophinep/chadu/master/chadu
chmod +rx /bin/chadu
echo "Adding alias.."
if [ `basename $SHELL` = "zsh" ]
then
  echo 'alias chadu=". chadu"' >> ~/.zshrc
else
  echo 'alias chadu=". chadu"' >> ~/.bashrc
fi
echo "chadu installation completed."
echo -e '''
Thanks, for downloading chadu..
For reporting issues, visit: https://github.com/jophinep/chadu/issues
Or you can write to "jophinep@gmail.com"
We appriciate your FEEDBACK.. as well

--
With Regards,
Jophine Pranjal'''
